# todo-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  labels:
    app: todo
spec:
  replicas: 2  # Pod 2개 생성
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
      - name: todo
        image: dwa010301/todo-app:v1  # 여러분의 이미지로 변경하세요
        ports:
        - containerPort: 8000
